name: pokedex
description: Un elegante y moderno Pokédex construido con Flutter. Explora, descubre y aprende sobre tus Pokémon favoritos con una interfaz intuitiva y atractiva. ¡Perfecto para aficionados y maestros Pokémon por igual! Dale vida a tu aventura Pokémon con esta aplicación interactiva.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.3
  http: ^1.1.0
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.7
  recase: ^4.1.0
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
